### ISSUE TITLE
keybind list too long

### ISSUE THREAD

**Issue by ghost** [dries007/TapeMouse#2]
When using /tapemouse to see what the correct key is, the list is simply too long. I can only see a quarter of all keys due to MC's short chat log. Perhaps adding pages or simply not showing the ones that are currently unbound ("NONE") could do the trick.

For example, I wanted to use left mouse ( it's attack for anyone reading this) but since I couldn't actually see it in the list I didn't know what the correct key would be. For some mods this could be an issue if you can't guess what it could be.

**Comment by dries007** [comment]
Pages is not possible in tab complete, and I think silly and complex for the help text.
The hiding of NONE seems like the best idea.

**Comment by ghost** [comment]
Glad to see it implemented, thanks!

**Comment by Awesomepotamus** [comment]
This is still an issue in some more heavily modded packs. For example, I'm unable to see the keys for clicks in FTB Stoneblock 2.

**Comment by ghost** [comment]
Left click, was "attack" as previously mentioned, unless you meant right click? A current option is to unbind unneeded keys so that the one you want is the only one listed.

**Comment by Awesomepotamus** [comment]
I was looking for "use" for right-click, since that's so common in that type of pack. What about putting the mouse buttons (attack/use/middle(?)) at the bottom of the list, so that no matter how long the list is, they are always visible?
