### ISSUE TITLE
Suggestion: Allow mod usage when in chat GUI

### ISSUE THREAD

**Issue by staridiot** [dries007/TapeMouse#7]
I like this mod, but I can't seem to use it effectively because it pauses when I open the chat window. When I tab out of Minecraft, I typically open the chat window to prevent input to Minecraft that would mess up my orientation. I don't know if this is a limitation with the key emulation or if this is intentional, but it's almost impossible to alt-tab out of Minecraft without screwing up something (at least for me). Another thing is, when I turn off my display to leave my computer on over night, Windows does something and screws up the game, this is why I can't use external software like Razer Synapse. I have the same issue here, because the game accepts inputs because a GUI isn't open. Even if this is a config edit, I'd like to see this.

**Comment by staridiot** [comment]
[Here is a quick demonstration](https://www.youtube.com/watch?v=iZJKNGuOK78) of me attempting to minimize my game after tabbing-out, you can see the game just grabs my mouse and doesn't allow me to minimize it.

**Comment by Claycorp** [comment]
You can't open chat or another GUI and continue to interact as the focus is now on that UI. This is a limitation of the game not the mod and isn't removable as removing it will make it impossible to close or stop the mod as the UI system in minecraft isn't selectable after it's opened.

The rest is your computer, it has nothing to do with this mod. Figure out whatever your computer is doing (likely going to sleep/hibernation) and disable it.
